<a href="https://colab.research.google.com/github/Vishal0Nagarajan/Flight-Delay-Prediction/blob/master/DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive

In [ ]:
import pandas as pd
import os
import json
import dask.dataframe as dd
import time
from datetime import datetime

In [ ]:
l = list()
req_airports = ['ATL','CLT','DEN','DFW','EWR','IAH','JFK','LAS','LAX','MCO','MIA','ORD','PHX','SEA','SFO']
path1 = 'drive/My Drive/Flight Data/2016_original/2016/'
for root, dirs, files in os.walk(path1):
  for file_ in files:
    if file_.endswith(".csv"):
      print(path1+file_)
      df = dd.read_csv(os.path.join(root, file_), sep = ',', error_bad_lines = False, dtype = 'unicode')
      X = df[df['Origin'].isin(req_airports) & df['Dest'].isin(req_airports)] 
      l.append(X[['Origin','Dest','FlightDate','Quarter','Year','Month','DayofMonth','DepTime','DepDel15','CRSDepTime','DepDelayMinutes','OriginAirportID','DestAirportID','ArrTime','CRSArrTime','ArrDel15','ArrDelayMinutes']])
path2 = 'drive/My Drive/Flight Data/2017_original/2017/'
for root, dirs, files in os.walk(path2):
  for file_ in files:
    if file_.endswith(".csv"):
      df = dd.read_csv(os.path.join(root, file_), sep = ',', error_bad_lines = False, dtype = 'unicode')
      X = df[df['Origin'].isin(req_airports) & df['Dest'].isin(req_airports)]
      l.append(X[['Origin','Dest','FlightDate','Quarter','Year','Month','DayofMonth','DepTime','DepDel15','CRSDepTime','DepDelayMinutes','OriginAirportID','DestAirportID','ArrTime','CRSArrTime','ArrDel15','ArrDelayMinutes']])
data = pd.concat(l)
data = data.dropna()
data = data.drop_duplicates(keep = 'first')
data = data.reset_index(drop = True)
l.clear()
data

ValueError: ignored

In [ ]:
path3 = 'drive/My Drive/weather/'
li = list()
for a in range(len(os.listdir(path3))):
  f = path3+os.listdir(path3)[a]+'/'
  for root, dirs, files in os.walk(f):
    for file_ in files:
      if (file_.startswith('2016') | file_.startswith('2017')):
        print(f+file_)
        dat = json.load(open(f+file_, 'rb'))
        del dat['data']['request']
        req_weather = ['windspeedKmph', 'winddirDegree', 'weatherCode', 'precipMM', 'visibility', 'pressure', 'cloudcover', 'DewPointF', 'WindGustKmph', 'tempF', 'WindChillF', 'humidity', 'date', 'time', 'airport']
        hourly_keys=list(dat['data']['weather'][0]['hourly'][0].keys())
        hourly_req = [i for i in hourly_keys if i in req_weather]
        myDict = {key:None for key in hourly_req}
        myDict['date'] = None
        myDict['airport'] = str(path3+os.listdir(path3)[a][-3:])     
        for k in range(31):
          try:
            myDict['date'] = dat['data']['weather'][k]['date']
          except IndexError:
            break
          for i in range(24):
            myDict.update({key : dat['data']['weather'][0]['hourly'][i][key] for key in hourly_req})
            d2 = pd.DataFrame(myDict, index = [0])
            d2 = d2.reset_index(drop = True)
            li.append(d2)
d_final = pd.concat(li)
d_final = d_final.reset_index(drop = True)
d_final['airport'] = d_final['airport'].apply(lambda x : x[-3:])
d_final

FileNotFoundError: ignored

In [ ]:
data.to_csv('drive/My Drive/data.csv')
d_final.to_csv('drive/My Drive/d_final.csv')

In [ ]:
data = pd.read_csv('drive/My Drive/data.csv', index_col = 0)
d_final = pd.read_csv('drive/My Drive/d_final.csv', index_col = 0)

/usr/local/lib/python3.6/dist-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [ ]:
data['DepTime'] = data['DepTime'].apply(lambda x : str(int(int(x)/100)) if str(int(int(x)/100))!='24' else '0')
data['ArrTime'] = data['ArrTime'].apply(lambda x : str(int(int(x)/100)) if str(int(int(x)/100))!='24' else '0')
d_final['time'] = d_final['time'].apply(lambda x : str(int(int(x)/100)) if str(int(int(x)/100))!='24' else '0')
df_merge = pd.merge(data, d_final, left_on = ['FlightDate', 'Origin', 'DepTime'], right_on = ['date', 'airport', 'time'], how = 'left')
df_merge_final = pd.merge(df_merge, d_final, left_on = ['FlightDate', 'Dest', 'ArrTime'], right_on = ['date', 'airport', 'time'], how = 'left')
df_merge_final

        Origin Dest  FlightDate  ...  time_y      date_y  airport_y
0          LAX  LAS  2016-11-05  ...      10  2016-11-05        LAS
1          DFW  ATL  2016-11-05  ...      16  2016-11-05        ATL
2          ATL  CLT  2016-11-05  ...      14  2016-11-05        CLT
3          CLT  ATL  2016-11-05  ...      16  2016-11-05        ATL
4          LAX  SEA  2016-11-05  ...      10  2016-11-05        SEA
...        ...  ...         ...  ...     ...         ...        ...
1851428    IAH  DFW  2017-10-28  ...      11  2017-10-28        DFW
1851429    DFW  IAH  2017-10-07  ...      14  2017-10-07        IAH
1851430    DFW  IAH  2017-10-14  ...      14  2017-10-14        IAH
1851431    DFW  IAH  2017-10-21  ...      14  2017-10-21        IAH
1851432    DFW  IAH  2017-10-28  ...      14  2017-10-28        IAH

[1851433 rows x 47 columns]

In [ ]:
df_merge_final.to_csv('drive/My Drive/DataPreprocessing.csv')